using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using BepInEx;
using BepInEx.Configuration;
using HarmonyLib;
using NineSolsAPI;
using NineSolsAPI.Utils;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace JinMultiplier;

[BepInDependency(NineSolsAPICore.PluginGUID)]
[BepInPlugin(MyPluginInfo.PLUGIN_GUID, MyPluginInfo.PLUGIN_NAME, MyPluginInfo.PLUGIN_VERSION)]
public class JinMultiplier : BaseUnityPlugin {
    // https://docs.bepinex.dev/articles/dev_guide/plugin_tutorial/4_configuration.html
    public ConfigEntry<int> jinDropMultiplier = null!;
    public ConfigEntry<int> tuwMultiplier = null!;
    public ConfigEntry<int> recycleMultiplier = null!;

    private Harmony harmony = null!;

    public static JinMultiplier Instance = null!;

    private void Awake() {
        Log.Init(Logger);
        RCGLifeCycle.DontDestroyForever(gameObject);

        // Load patches from any class annotated with @HarmonyPatch
        harmony = Harmony.CreateAndPatchAll(typeof(JinMultiplier).Assembly);

        Instance = this;

        jinDropMultiplier = Config.Bind("Multipliers", "Jin Drop Multiplier", 1,
            "Multiplies the value of jin particles dropped on the ground by enemies, chests, and other breakable objects.");

        tuwMultiplier = Config.Bind("Multipliers", "Transmute Unto Wealth Multiplier", 1,
            "Multiplies the 10 bonus jin that you get from killing an enemy with a talisman while Transmute Unto Wealth is equipped." +
            "\n\nLike TUW itself, this is separate from the jin particles the enemy drops on the ground.");

        recycleMultiplier = Config.Bind("Multipliers", "Recycling Multiplier", 1,
            "Multiplies the jin generated by recycling items at the 3D Printer in Four Seasons Pavilion.");

        Logger.LogInfo($"Plugin {MyPluginInfo.PLUGIN_GUID} is loaded!");
    }

    private void OnDestroy() {
        // Make sure to clean up resources here to support hot reloading

        harmony.UnpatchSelf();
    }
}